# Generated by Django 2.2 on 2023-07-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=200)),
                ('story_text', models.CharField(max_length=10000)),
                ('story_image', models.CharField(default='https://st2.depositphotos.com/4497765/7454/v/450/depositphotos_74540551-stock-illustration-pow-comic-book-cartoon-expression.jpg', max_length=2000)),
            ],
        ),
    ]
