# Generated by Django 2.2 on 2023-07-18 04:08

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('madlibs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text', jsonfield.fields.JSONField()),
                ('story_words', jsonfield.fields.JSONField()),
                ('story_id', models.IntegerField(null=True)),
            ],
        ),
    ]
